version: '3.9'
volumes:
  postgres-data:
services:
  authserver:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: authserver
    environment:
      - NODE_ENV="development"
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
      - 5555:5555
    volumes:
      - ./app:/app
    depends_on:
      - postgresql
  postgresql:
     image: postgres:12
     container_name: auth-db
     environment:
       - POSTGRES_USER=root
       - POSTGRES_PASSWORD=root
       - POSTGRES_DB=authdb 
     ports:
       - 5432:5432
     volumes:
       - postgres-data:/var/lib/postgresql/data
     env_file:
       - ./app/.env
