version: '3.9'
services:
  authserver:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: authserver
    environment:
      - NODE_ENV="development"
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
